### PR TITLE
Missing number java

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
#1

### CODE REVIEW

**Comment by uvansh** [comment]
This is a problem not an algorithm...

**Comment by Brijeshthummar02** [comment]
u mean we need only algos.
i gone through your repo and it also contains problem soln so i thought why not i.

**Comment by uvansh** [comment]
> u mean we need only algos.
> i gone through your repo and it also contains problem soln so i thought why not i.

Yes it contains but i specifically asked for algos only

**Comment by Brijeshthummar02** [comment]
got it.

**Pull request closed without merging**
